language: ruby
os:
  - linux
  # - osx
before_install:
  - gem install bundler -v 1.10.6
  - bundle install
rvm:
  - 2.6.5
  - 2.5.7
  - 2.4.9
  - 2.3.8
  - 2.2.2
notifications:
  email: false
sudo: required
dist: trusty
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc
script:
  - echo CFLAGS = $CFLAGS
  - echo cflags = $cflags
  - bundle exec rake compile
  - env VERBOSE=1 bundle exec rspec --format documentation
  - gem uninstall -x iodine
  - rake build
  - find pkg/iodine-*.gem -exec gem install -V {} +
